# generated by datamodel-codegen:
#   filename:  aggregates_minute.json
#   timestamp: 2021-07-10T12:18:41+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    ev: str
    sym: str
    v: int
    av: int
    op: float
    vw: float
    o: float
    c: float
    h: float
    l: float
    a: float
    z: int
    s: int
    e: int
