# generated by datamodel-codegen:
#   filename:  snapshot.json
#   timestamp: 2021-07-09T13:21:53+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Day(BaseModel):
    c: int
    h: int
    l: int
    o: int
    v: int
    vw: int


class LastQuote(BaseModel):
    P: float
    S: int
    p: float
    s: int
    t: int


class LastTrade(BaseModel):
    c: Optional[List[int]]
    i: str
    p: float
    s: int
    t: int
    x: int


class Min(BaseModel):
    av: int
    c: float
    h: float
    l: float
    o: float
    v: int
    vw: float


class PrevDay(BaseModel):
    c: float
    h: float
    l: float
    o: float
    v: int
    vw: float


class Model(BaseModel):
    day: Day
    lastQuote: LastQuote
    lastTrade: LastTrade
    min: Min
    prevDay: PrevDay
    ticker: str
    todaysChange: float
    todaysChangePerc: float
    updated: int
