# generated by datamodel-codegen:
#   filename:  tickerlist.json
#   timestamp: 2021-07-09T13:35:50+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class TickerlistItem(BaseModel):
    name: str
    exchange: str
    symbol: str
    change: float
    changePerc: float


class Model(BaseModel):
    tickerlist: List[TickerlistItem]
