# generated by datamodel-codegen:
#   filename:  tickerlist.json
#   timestamp: 2021-07-09T13:35:50+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class TickerlistItem(BaseModel):
    name: str
    exchange: str
    symbol: str
    change: Optional[float]
    change_perc: Optional[float]


class TickerlistResponse(BaseModel):
    tickerlist: List[TickerlistItem]
