version: "3"
services:
  api:
    build: .
    ports:
      - "5050:5050"
    volumes:
      - .:/app
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis:/data
      - ./redis-dump:/var/lib/redis
