from fastapi import APIRouter

from services import get_tickers_metadata
from utils.constants import Tickers
from utils.custom_types import (
    RecommendationsModel,
    RecommendationsMongoModel,
    RequestExtended,
    SnapshotModel,
    TickerlistModel,
)

api_router = APIRouter()


@api_router.get("/tickerlist", response_model=TickerlistModel)
def get_ticker_list(request: RequestExtended):
    """
    return list of tickers
    """
    tickers_metadata = get_tickers_metadata(request.app)
    params = {"tickers": ",".join(Tickers)}
    res = request.app.polygon.stocks_equities_snapshot_all_tickers(**params)
    for snapshot in res.tickers:
        s = SnapshotModel(**snapshot)
        tickers_metadata[s.ticker].update(
            {
                "change": s.todaysChange,
                "changePerc": s.todaysChangePerc,
            }
        )
    return {"tickerlist": list(tickers_metadata.values())}


@api_router.get("/recommendations", response_model=RecommendationsModel)
def get_recommendations(request: RequestExtended, limit: int = 50):
    """
    returns the latest recommendations generated by the algorithm.
    """
    results = request.app.db.recommendations.find().sort("_id", -1).limit(100)
    results = [RecommendationsMongoModel(**i) for i in results]
    recent_recommendations = []
    for period in results:
        period.set_fields()
        recent_recommendations.extend(period.recommendations)
    recent_recommendations = recent_recommendations[:limit]
    return {"results": recent_recommendations}


@api_router.get("/performance")
def get_performance(request: RequestExtended):
    """
    {
        performance: [
            {
                month: "July 2021",
                realized_pnl: 2.33,
                positions: [
                    {
                        ticker: "AAPL",
                        buy: 100,
                        sell: 150,
                        pnl, 50,
                        notes: "reached target price"
                    },
                    ...
                ]
            },
            ...
        ]
    }
    """
    pass
